#
# Author: Nasheb Ismaily
#
# All rights reserved - Do Not Redistribute


#!/usr/bin/expect

set user_name [lindex $argv 0]
set user_password [lindex $argv 1]
set ldap_password [lindex $argv 2]

spawn ldappasswd -H ldap://<ldap_host>:<ldap_port> -D cn=ldapadmin,dc=<domian>,dc=<domian>,dc=<domian> -w $ldap_password -S uid=$user_name,ou=People,dc=<domian>,dc=<domian>,dc=<domian>
expect "New password:"
send "$user_password\r"
expect "Re-enter new password:"
send "$user_password\r"
interact

