#
# Author: Nasheb Ismaily
#
# All rights reserved - Do Not Redistribute


#!/usr/bin/expect

set user_name [lindex $argv 0]
set user_password [lindex $argv 1]

spawn ambari-server sync-ldap --all
expect "Using python  /usr/bin/python"
expect "Syncing with LDAP..."
expect "Enter Ambari Admin login:"
send "$user_password\r"
expect "Enter Ambari Admin password:"
send "$user_password\r"
expect "Syncing all..."
expect "*"
interact

